# @package _global_

defaults:
  - /data/oil_rgb_20260202_3cls
  - /model/rtmsfdetr/rtv4_hgnetv2_m_distill
  - /runtime/default
  - /train/rtmsfdetr_default
  - /task/rtmsfdetr/base
  - _self_

data:
  rgb_normalize_mode: imagenet
train:
  model_alias: rtv4_hgnetv2_m_distill_det

  batch_size: 24
  epochs: 100
  num_classes: 3
  # Align to RT-DETRv4-M recipe.
  lr: 0.0005

