# @package _global_

# 双流 SMSFDETR：ASMF + EEMSA + ACAF + P2DBF(internal) + OrigStem Residual MS Branch Early Align
defaults:
  - /task/smsfdetr/oil_rgb_msi_20260202_3cls/smsfdetr_oil_rgb_msi_20260202_det_rtv4_hgnetv2_m_distill_dualstream_asmf_postblock_add_wbadd_c3c4c5_globalkv_pos2d_acaf_p2dbf_internal_eemsa_s1s2s3s4
  - /model/smsfdetr/modules/origstem_residual_msbranch_shared_hgstem_inner_fixed_band_cmda_b3_stem_cf_interactive
  - _self_

model:
  model_alias: rtv4_hgnetv2_m_distill_dualstream_asmf_postblock_add_wbadd_c3c4c5_globalkv_pos2d_acaf_p2dbf_internal_eemsa_s1s2s3s4_origstem_residual_msbranch_shared_hgstem_inner_fixed_band_cmda_b3_stem_cf_interactive

train:
  model_alias: rtv4_hgnetv2_m_distill_det_dualstream_asmf_postblock_add_wbadd_c3c4c5_globalkv_pos2d_acaf_p2dbf_internal_eemsa_s1s2s3s4_origstem_residual_msbranch_shared_hgstem_inner_fixed_band_cmda_b3_stem_cf_interactive
