# @package _global_

# ASMF + EEMSA + early-align
defaults:
  - /task/smsfdetr/oil_rgb_msi_20260202_3cls/smsfdetr_oil_rgb_msi_20260202_det_rtv4_hgnetv2_m_distill_dualstream_asmf
  - /model/smsfdetr/modules/eemsa_stage1_stage2_stage3_stage4
  - /model/smsfdetr/modules/origstem_residual_msbranch_shared_hgstem_inner_fixed_band_cmda_b3_stem_cf_interactive
  - _self_

model:
  model_alias: rtv4_hgnetv2_m_distill_dualstream_asmf_eemsa_earlyalign

train:
  model_alias: rtv4_hgnetv2_m_distill_det_dualstream_asmf_eemsa_earlyalign
