# @package _global_

# 阶段：双流等价基线 + (ACAF + P2DBF internal) + EEMSA(stage1~stage4)
defaults:
  - /task/smsfdetr/oil_rgb_msi_20260202_3cls/smsfdetr_oil_rgb_msi_20260202_det_rtv4_hgnetv2_m_distill_dualstream_c2former_postblock_add_wbadd_c3c4c5_globalkv_pos2d_eemsa_s1s2s3s4
  - _self_

model:
  model_alias: rtv4_hgnetv2_m_distill_dualstream_c2former_postblock_add_wbadd_c3c4c5_globalkv_pos2d_acaf_p2dbf_internal_eemsa_s1s2s3s4
  rtdetrv4_config: engines/models/rtmsfdetr/rtdetrv4/configs/rtv4/rtv4_hgnetv2_m_coco_acaf_p2dbf_internal.yml

train:
  model_alias: rtv4_hgnetv2_m_distill_det_dualstream_c2former_postblock_add_wbadd_c3c4c5_globalkv_pos2d_acaf_p2dbf_internal_eemsa_s1s2s3s4
