# @package _global_

# 双流 + EEMSA（阶段配置）：
# - 数据集: oil_rgb_msi_20260202_3cls
# - 基于 dualstream 等价基线，叠加 EEMSA(stage1~stage4)
defaults:
  - /task/smsfdetr/oil_rgb_msi_20260202_3cls/smsfdetr_oil_rgb_msi_20260202_det_rtv4_hgnetv2_m_distill_dualstream_asmf_postblock_add_wbadd_c3c4c5_globalkv_pos2d
  - /model/smsfdetr/modules/eemsa_stage1_stage2_stage3_stage4
  - _self_

model:
  model_alias: rtv4_hgnetv2_m_distill_dualstream_asmf_postblock_add_wbadd_c3c4c5_globalkv_pos2d_eemsa_s1s2s3s4

train:
  model_alias: rtv4_hgnetv2_m_distill_det_dualstream_asmf_postblock_add_wbadd_c3c4c5_globalkv_pos2d_eemsa_s1s2s3s4
