# @package _global_

# ASMF + ACAF + P2DBF(internal) + early-align
defaults:
  - /task/smsfdetr/oil_rgb_msi_20260202_3cls/smsfdetr_oil_rgb_msi_20260202_det_rtv4_hgnetv2_m_distill_dualstream_asmf
  - /model/smsfdetr/modules/acaf_p2dbf_internal
  - /model/smsfdetr/modules/origstem_residual_msbranch_shared_hgstem_inner_fixed_band_cmda_b3_stem_cf_interactive
  - _self_

model:
  model_alias: rtv4_hgnetv2_m_distill_dualstream_asmf_acaf_p2dbf_earlyalign
  rtdetrv4_config: engines/models/rtmsfdetr/rtdetrv4/configs/rtv4/rtv4_hgnetv2_m_coco_acaf_p2dbf_internal_stable_moda.yml
  backbone_ms_residual_stem:
    scale_init: 0.01
    align:
      num_keypoints: 5
      offset_scale: 1.5
      loss_weight: 0.01
      loss_offset_weight: 0.005
      loss_attn_entropy_weight: 0.0005
    stem_interactive:
      ref_shift_scale: 0.01
      scale_init: 0.002

train:
  model_alias: rtv4_hgnetv2_m_distill_det_dualstream_asmf_acaf_p2dbf_earlyalign
  amp: true
  batch_size: 4
