#!/usr/bin/env bash
set -euo pipefail

# One-shot panel generator:
#   - left : RGB + GT bboxes (+ optional predictions)
#   - right: heatmap overlay (+ optional GT/predictions)
#
# It assumes <repr_run_dir>/selection/overlay_heatmap already exists (generated by:
#   - repr_oil_heatmap.py (cluster->oil heatmap), or
#   - vis/featuremap_heatmap_rtmsfdetr.py (actual feature heatmap)
#
# Usage:
#   bash tools/cluster_analysis/run_panel_gt_pred_heatmap.sh <repr_run_dir> [device]
#
# Example:
#   bash tools/cluster_analysis/run_panel_gt_pred_heatmap.sh \
#     outputs/repr/rtmsfdetr/oil_val_fpn0_k32x16_rgb_msi_20260108-195440 cuda:0
#
# Tunables (env vars):
#   ANN=...                          (optional; default: auto-derive from meta.json->config.yaml)
#   SPLIT=train|val|test             (optional; default: meta.json split or val)
#   SHOW=oil|all                     (default: oil; which GT boxes to draw)
#   OIL_NAMES="oil"                  (default: oil; space-separated)
#   DRAW_BOXES_ON_RIGHT=1            (default: 1)
#   LIMIT=0                          (default: 0; 0 => no limit)
#   OUTPUT_DIR=...                   (optional override; default: <run_dir>/selection/panel)
#
#   PRED_SHOW=oil|all                (default: oil)
#   PRED_SCORE_THR=0.3               (default: 0.3)
#   PRED_MAX_DETS=100                (default: 100)
#   PRED_BOX_WIDTH=2                 (default: 2)
#   PRED_COLOR="0,255,255"           (default: cyan)
#   PRED_SHOW_SCORE=0                (default: 0; 1 draws score text)
#   PRED_BATCH_SIZE=1                (default: 1)
#   PRED_AMP=0                       (default: 0; 1 enables AMP on CUDA)
#   PRED_USE_EMA=0                   (default: 0; 1 prefers ema weights if present)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
cd "${REPO_ROOT}"

RUN_DIR="${1:-}"
DEVICE="${2:-cuda}"

if [[ -z "${RUN_DIR}" ]]; then
  echo "Usage: $0 <repr_run_dir> [device]" >&2
  exit 2
fi

RUN_DIR="${RUN_DIR%/}"
if [[ ! -d "${RUN_DIR}" ]]; then
  echo "ERROR: repr run dir not found: ${RUN_DIR}" >&2
  exit 2
fi

ANN_PATH="${ANN:-}"
SPLIT="${SPLIT:-}"
SHOW="${SHOW:-oil}"
OIL_NAMES="${OIL_NAMES:-oil}"
DRAW_BOXES_ON_RIGHT="${DRAW_BOXES_ON_RIGHT:-1}"
LIMIT="${LIMIT:-0}"
OUTPUT_DIR="${OUTPUT_DIR:-}"

PRED_SHOW="${PRED_SHOW:-oil}"
PRED_SCORE_THR="${PRED_SCORE_THR:-0.3}"
PRED_MAX_DETS="${PRED_MAX_DETS:-100}"
PRED_BOX_WIDTH="${PRED_BOX_WIDTH:-2}"
PRED_COLOR="${PRED_COLOR:-0,255,255}"
PRED_SHOW_SCORE="${PRED_SHOW_SCORE:-0}"
PRED_BATCH_SIZE="${PRED_BATCH_SIZE:-1}"
PRED_AMP="${PRED_AMP:-0}"
PRED_USE_EMA="${PRED_USE_EMA:-0}"

OIL_NAMES_ARR=()
read -r -a OIL_NAMES_ARR <<< "${OIL_NAMES}"

CMD=(python tools/cluster_analysis/repr_oil_heatmap_panel.py
  --run-dir "${RUN_DIR}"
  --show "${SHOW}"
  --pred-device "${DEVICE}"
  --pred-show "${PRED_SHOW}"
  --pred-score-thr "${PRED_SCORE_THR}"
  --pred-max-dets "${PRED_MAX_DETS}"
  --pred-box-width "${PRED_BOX_WIDTH}"
  --pred-color "${PRED_COLOR}"
  --pred-batch-size "${PRED_BATCH_SIZE}"
  --draw-preds
)

if [[ -n "${ANN_PATH}" ]]; then
  CMD+=(--ann "${ANN_PATH}")
fi
if [[ -n "${SPLIT}" ]]; then
  CMD+=(--split "${SPLIT}")
fi
if [[ "${DRAW_BOXES_ON_RIGHT}" == "1" ]]; then
  CMD+=(--draw-boxes-on-right)
fi
if [[ "${LIMIT}" != "0" ]]; then
  CMD+=(--limit "${LIMIT}")
fi
if [[ -n "${OUTPUT_DIR}" ]]; then
  CMD+=(--output-dir "${OUTPUT_DIR}")
fi
if [[ "${#OIL_NAMES_ARR[@]}" -gt 0 ]]; then
  CMD+=(--oil-names "${OIL_NAMES_ARR[@]}")
fi
if [[ "${PRED_AMP}" == "1" ]]; then
  CMD+=(--pred-amp)
fi
if [[ "${PRED_SHOW_SCORE}" == "1" ]]; then
  CMD+=(--pred-show-score)
fi
if [[ "${PRED_USE_EMA}" == "1" ]]; then
  CMD+=(--pred-use-ema)
fi

printf 'cmd: %q ' "${CMD[@]}"; echo
"${CMD[@]}"
