# @package _global_

model:
  model_alias: rfdetr_nano
  encoder: dinov2_windowed_small
  out_feature_indexes: [3, 6, 9, 12]
  dec_layers: 2
  two_stage: true
  projector_scale: ["P4"]
  hidden_dim: 256
  patch_size: 16
  num_windows: 2
  sa_nheads: 8
  ca_nheads: 16
  dec_n_points: 2
  bbox_reparam: true
  lite_refpoint_refine: true
  layer_norm: true
  amp: true
  num_classes: 90
  pretrain_weights: weights/rfdetr/rf-detr-nano.pth
  img_size: 384
  group_detr: 13
  gradient_checkpointing: false
  positional_encoding_size: 24
  ia_bce_loss: true
  cls_loss_coef: 1.0
  segmentation_head: false
  mask_downsample_ratio: 4
  num_queries: 300
  num_select: 300
