# @package _global_

model:
  model_alias: rfdetr_seg_preview
  encoder: dinov2_windowed_small
  out_feature_indexes: [3, 6, 9, 12]
  dec_layers: 4
  two_stage: true
  projector_scale: ["P4"]
  hidden_dim: 256
  patch_size: 12
  num_windows: 2
  sa_nheads: 8
  ca_nheads: 16
  dec_n_points: 2
  bbox_reparam: true
  lite_refpoint_refine: true
  layer_norm: true
  amp: true
  num_classes: 90
  # 需要在本地放置或改写为可访问路径
  pretrain_weights: weights/rfdetr/rf-detr-seg-preview.pt
  img_size: 432
  group_detr: 13
  gradient_checkpointing: false
  positional_encoding_size: 36
  ia_bce_loss: true
  cls_loss_coef: 1.0
  segmentation_head: true
  mask_downsample_ratio: 4
  num_queries: 200
  num_select: 200
